spring:
  application:
    name: demo-core-a-provider

server:
  port: 20002

dubbo:
  application:
    name: demo-core-a-provider
    qos-port: 21002
  protocol:
    name: dubbo
    port: 22002
  registry:
    address: nacos://127.0.0.1:8848