nacos:
  config:
    server-addr: 127.0.0.1:18848
    username: nacos
    password: nacos

# 以下内容上线时配置到Nacos，并从本地删除
spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid:
        filters: config
        connection-properties: config.decrypt=true
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
          username: coffee
          password: l2YHrI2sQjLG9epSXzB+GZApL9CJXzsgPa1VaqMlPYkGBY/WxNB6RKndU1Z/7AcRIVQBnvcE7xmL1slnSN8yLw==
  redis:
    cluster:
      nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
      max-redirects: 3
    password:
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8