spring:
  application:
    name: demo-core-a-provider
  profiles:
    active: dev

server:
  port: 28010

nacos:
  config:
    bootstrap:
      enable: true
    namespace: ${spring.profiles.active}
    data-ids: ${spring.application.name}.yml
    type: yaml
    auto-refresh: true
    group: DEMO_GROUP

dubbo:
  application:
    name: ${spring.application.name}
    qos-port: 28011
    register-mode: instance
  protocols:
    tri:
      name: tri
      port: 28012
      ext-protocol: dubbo,
    rest:
      name: rest
      port: 28013
  registry:
    address: nacos://${nacos.config.server-addr}?username=${nacos.config.username}&password=${nacos.config.password}
    group: ${nacos.config.group}
    parameters:
      namespace: ${spring.profiles.active}
