spring:
  application:
    name: demo-core-b-provider

server:
  port: 20012

dubbo:
  application:
    name: demo-core-b-provider
    qos-port: 21012
  protocols:
    dubbo:
      name: dubbo
      port: 22012
    rest:
      name: rest
      port: 23012
  registry:
    address: nacos://127.0.0.1:8848
